language: scala
scala:
  - "2.11.7"
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
install:
  - "rm -rf ~/.nvm"
  - "curl -L https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh"
  - "source ~/.nvm/nvm.sh"
  - "nvm install 0.10"
  - "nvm use 0.10"
script:
  - "npm install"
  - sbt test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
